export const GET_ADMIN_ABOUT_REQUEST = "GET_ADMIN_ABOUT_REQUEST";
export const GET_ADMIN_ABOUT_SUCCESS = "GET_ADMIN_ABOUT_SUCCESS";
export const GET_ADMIN_ABOUT_FAIL = "GET_ADMIN_ABOUT_FAIL";

export const ADD_ABOUTHEADER_ADMIN_REQUEST = "ADD_ABOUTHEADER_ADMIN_REQUEST";
export const ADD_ABOUTHEADER_ADMIN_SUCCESS = "ADD_ABOUTHEADER_ADMIN_SUCCESS";
export const ADD_ABOUTHEADER_ADMIN_FAIL = "ADD_ABOUTHEADER_ADMIN_FAIL";
export const ADD_ABOUTHEADER_ADMIN_RESET = "ADD_ABOUTHEADER_ADMIN_RESET";

export const ADD_ABOUTMISSION_ADMIN_REQUEST = "ADD_ABOUTMISSION_ADMIN_REQUEST";
export const ADD_ABOUTMISSION_ADMIN_SUCCESS = "ADD_ABOUTMISSION_ADMIN_SUCCESS";
export const ADD_ABOUTMISSION_ADMIN_FAIL = "ADD_ABOUTMISSION_ADMIN_FAIL";
export const ADD_ABOUTMISSION_ADMIN_RESET = "ADD_ABOUTMISSION_ADMIN_RESET";

export const ADD_ABOUTWEDO_ADMIN_REQUEST = "ADD_ABOUTWEDO_ADMIN_REQUEST";
export const ADD_ABOUTWEDO_ADMIN_SUCCESS = "ADD_ABOUTWEDO_ADMIN_SUCCESS";
export const ADD_ABOUTWEDO_ADMIN_FAIL = "ADD_ABOUTWEDO_ADMIN_FAIL";
export const ADD_ABOUTWEDO_ADMIN_RESET = "ADD_ABOUTWEDO_ADMIN_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";