export const GET_ADMIN_ADMIN_REQUEST = "GET_ADMIN_ADMIN_REQUEST";
export const GET_ADMIN_ADMIN_SUCCESS = "GET_ADMIN_ADMIN_SUCCESS";
export const GET_ADMIN_ADMIN_FAIL = "GET_ADMIN_ADMIN_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";