export const GET_ADMIN_ADMIN_REQUEST = "GET_ADMIN_ADMIN_REQUEST";
export const GET_ADMIN_ADMIN_SUCCESS = "GET_ADMIN_ADMIN_SUCCESS";
export const GET_ADMIN_ADMIN_FAIL = "GET_ADMIN_ADMIN_FAIL";

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const LOAD_ADMIN_REQUEST = "LOAD_ADMIN_REQUEST"; 
export const LOAD_ADMIN_SUCCESS = "LOAD_ADMIN_SUCCESS"; 
export const LOAD_ADMIN_FAIL = "LOAD_ADMIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FALI";

export const ADD_NEW_ADMIN_REQUEST = "ADD_NEW_ADMIN_REQUEST";
export const ADD_NEW_ADMIN_SUCCESS = "ADD_NEW_ADMIN_SUCCESS";
export const ADD_NEW_ADMIN_FAIL = "ADD_NEW_ADMIN_FAIL";
export const ADD_NEW_ADMIN_RESET = "ADD_NEW_ADMIN_RESET";

export const  ADMIN_DELETE_REQUEST = "ADMIN_DELETE_REQUEST";
export const  ADMIN_DELETE_SUCCESS = "ADMIN_DELETE_SUCCESS";
export const  ADMIN_DELETE_FAIL = "ADMIN_DELETE_FAIL";
export const  ADMIN_DELETE_RESET = "ADMIN_DELETE_RESET";

export const  ADMIN_UPDATE_REQUEST = "ADMIN_UPDATE_REQUEST";
export const  ADMIN_UPDATE_SUCCESS = "ADMIN_UPDATE_SUCCESS";
export const  ADMIN_UPDATE_FAIL = "ADMIN_UPDATE_FAIL";
export const  ADMIN_UPDATE_RESET = "ADMIN_UPDATE_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";