export const GET_ADMIN_CONSUMER_REQUEST = "GET_ADMIN_CONSUMER_REQUEST";
export const GET_ADMIN_CONSUMER_SUCCESS = "GET_ADMIN_CONSUMER_SUCCESS";
export const GET_ADMIN_CONSUMER_FAIL = "GET_ADMIN_CONSUMER_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";