export const GET_ADMIN_CONTACT_REQUEST = "GET_ADMIN_CONTACT_REQUEST";
export const GET_ADMIN_CONTACT_SUCCESS = "GET_ADMIN_CONTACT_SUCCESS";
export const GET_ADMIN_CONTACT_FAIL = "GET_ADMIN_CONTACT_FAIL";


export const ADD_CONTACT_ADMIN_REQUEST = "ADD_CONTACT_ADMIN_REQUEST";
export const ADD_CONTACT_ADMIN_SUCCESS = "ADD_CONTACT_ADMIN_SUCCESS";
export const ADD_CONTACT_ADMIN_FAIL = "ADD_CONTACT_ADMIN_FAIL";
export const ADD_CONTACT_ADMIN_RESET = "ADD_CONTACT_ADMIN_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";