export const GET_ADMIN_CONTACT_REQUEST = "GET_ADMIN_CONTACT_REQUEST";
export const GET_ADMIN_CONTACT_SUCCESS = "GET_ADMIN_CONTACT_SUCCESS";
export const GET_ADMIN_CONTACT_FAIL = "GET_ADMIN_CONTACT_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";