export const GET_ADMIN_DISCOUNT_REQUEST = "GET_ADMIN_DISCOUNT_REQUEST";
export const GET_ADMIN_DISCOUNT_SUCCESS = "GET_ADMIN_DISCOUNT_SUCCESS";
export const GET_ADMIN_DISCOUNT_FAIL = "GET_ADMIN_DISCOUNT_FAIL";

export const  DISCOUNT_APPROVE_REQUEST = "DISCOUNT_APPROVE_REQUEST";
export const  DISCOUNT_APPROVE_SUCCESS = "DISCOUNT_APPROVE_SUCCESS";
export const  DISCOUNT_APPROVE_FAIL = "DISCOUNT_APPROVE_FAIL";
export const  DISCOUNT_APPROVE_RESET = "DISCOUNT_APPROVE_RESET";

export const  CREATE_COUPON_REQUEST = "CREATE_COUPON_REQUEST";
export const  CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS";
export const  CREATE_COUPON_FAIL = "CREATE_COUPON_FAIL";

export const  DISCOUNT_DELETE_REQUEST = "DISCOUNT_DELETE_REQUEST";
export const  DISCOUNT_DELETE_SUCCESS = "DISCOUNT_DELETE_SUCCESS";
export const  DISCOUNT_DELETE_FAIL = "DISCOUNT_DELETE_FAIL";
export const  DISCOUNT_DELETE_RESET = "DISCOUNT_DELETE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";