export const GET_ADMIN_HOME_REQUEST = "GET_ADMIN_HOME_REQUEST";
export const GET_ADMIN_HOME_SUCCESS = "GET_ADMIN_HOME_SUCCESS";
export const GET_ADMIN_HOME_FAIL = "GET_ADMIN_HOME_FAIL";

export const ADD_HOMEHEADER_ADMIN_REQUEST = "ADD_HOMEHEADER_ADMIN_REQUEST";
export const ADD_HOMEHEADER_ADMIN_SUCCESS = "ADD_HOMEHEADER_ADMIN_SUCCESS";
export const ADD_HOMEHEADER_ADMIN_FAIL = "ADD_HOMEHEADER_ADMIN_FAIL";
export const ADD_HOMEHEADER_ADMIN_RESET = "ADD_HOMEHEADER_ADMIN_RESET";

export const ADD_HOMEHEADERCARD_ADMIN_REQUEST = "ADD_HOMEHEADERCARD_ADMIN_REQUEST";
export const ADD_HOMEHEADERCARD_ADMIN_SUCCESS = "ADD_HOMEHEADERCARD_ADMIN_SUCCESS";
export const ADD_HOMEHEADERCARD_ADMIN_FAIL = "ADD_HOMEHEADERCARD_ADMIN_FAIL";
export const ADD_HOMEHEADERCARD_ADMIN_RESET = "ADD_HOMEHEADERCARD_ADMIN_RESET";

export const ADD_HOMEBATTARIE_ADMIN_REQUEST = "ADD_HOMEBATTARIE_ADMIN_REQUEST";
export const ADD_HOMEBATTARIE_ADMIN_SUCCESS = "ADD_HOMEBATTARIE_ADMIN_SUCCESS";
export const ADD_HOMEBATTARIE_ADMIN_FAIL = "ADD_HOMEBATTARIE_ADMIN_FAIL";
export const ADD_HOMEBATTARIE_ADMIN_RESET = "ADD_HOMEBATTARIE_ADMIN_RESET";

export const ADD_HOMECONTACT_ADMIN_REQUEST = "ADD_HOMECONTACT_ADMIN_REQUEST";
export const ADD_HOMECONTACT_ADMIN_SUCCESS = "ADD_HOMECONTACT_ADMIN_SUCCESS";
export const ADD_HOMECONTACT_ADMIN_FAIL = "ADD_HOMECONTACT_ADMIN_FAIL";
export const ADD_HOMECONTACT_ADMIN_RESET = "ADD_HOMECONTACT_ADMIN_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";