export const GET_ADMIN_HOME_REQUEST = "GET_ADMIN_HOME_REQUEST";
export const GET_ADMIN_HOME_SUCCESS = "GET_ADMIN_HOME_SUCCESS";
export const GET_ADMIN_HOME_FAIL = "GET_ADMIN_HOME_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";