export const GET_ADMIN_ORDER_REQUEST = "GET_ADMIN_ORDER_REQUEST";
export const GET_ADMIN_ORDER_SUCCESS = "GET_ADMIN_ORDER_SUCCESS";
export const GET_ADMIN_ORDER_FAIL = "GET_ADMIN_ORDER_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";