export const GET_ADMIN_ORDER_REQUEST = "GET_ADMIN_ORDER_REQUEST";
export const GET_ADMIN_ORDER_SUCCESS = "GET_ADMIN_ORDER_SUCCESS";
export const GET_ADMIN_ORDER_FAIL = "GET_ADMIN_ORDER_FAIL";

export const UPDATE_ADMIN_ORDER_REQUEST = "UPDATE_ADMIN_ORDER_REQUEST";
export const UPDATE_ADMIN_ORDER_SUCCESS = "UPDATE_ADMIN_ORDER_SUCCESS";
export const UPDATE_ADMIN_ORDER_FAIL = "UPDATE_ADMIN_ORDER_FAIL";
export const UPDATE_ADMIN_ORDER_RESET = "UPDATE_ADMIN_ORDER_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";