export const GET_ADMIN_PRODUCT_REQUEST = "GET_ADMIN_PRODUCT_REQUEST";
export const GET_ADMIN_PRODUCT_SUCCESS = "GET_ADMIN_PRODUCT_SUCCESS";
export const GET_ADMIN_PRODUCT_FAIL = "GET_ADMIN_PRODUCT_FAIL";

export const ADD_PRODUCTHEADER_ADMIN_REQUEST = "ADD_PRODUCTHEADER_ADMIN_REQUEST";
export const ADD_PRODUCTHEADER_ADMIN_SUCCESS = "ADD_PRODUCTHEADER_ADMIN_SUCCESS";
export const ADD_PRODUCTHEADER_ADMIN_FAIL = "ADD_PRODUCTHEADER_ADMIN_FAIL";
export const ADD_PRODUCTHEADER_ADMIN_RESET = "ADD_PRODUCTHEADER_ADMIN_RESET";

export const ADD_BATTERY_ADMIN_REQUEST = "ADD_BATTERY_ADMIN_REQUEST";
export const ADD_BATTERY_ADMIN_SUCCESS = "ADD_BATTERY_ADMIN_SUCCESS";
export const ADD_BATTERY_ADMIN_FAIL = "ADD_BATTERY_ADMIN_FAIL";
export const ADD_BATTERY_ADMIN_RESET = "ADD_BATTERY_ADMIN_RESET";

export const ADD_BATTERYCARD_ADMIN_REQUEST = "ADD_BATTERYCARD_ADMIN_REQUEST";
export const ADD_BATTERYCARD_ADMIN_SUCCESS = "ADD_BATTERYCARD_ADMIN_SUCCESS";
export const ADD_BATTERYCARD_ADMIN_FAIL = "ADD_BATTERYCARD_ADMIN_FAIL";
export const ADD_BATTERYCARD_ADMIN_RESET = "ADD_BATTERYCARD_ADMIN_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";