export const GET_ADMIN_RESELLER_REQUEST = "GET_ADMIN_RESELLER_REQUEST";
export const GET_ADMIN_RESELLER_SUCCESS = "GET_ADMIN_RESELLER_SUCCESS";
export const GET_ADMIN_RESELLER_FAIL = "GET_ADMIN_RESELLER_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";