export const GET_ADMIN_RESELLER_REQUEST = "GET_ADMIN_RESELLER_REQUEST";
export const GET_ADMIN_RESELLER_SUCCESS = "GET_ADMIN_RESELLER_SUCCESS";
export const GET_ADMIN_RESELLER_FAIL = "GET_ADMIN_RESELLER_FAIL";

export const  RESELLER_APPROVE_REQUEST = "RESELLER_APPROVE_REQUEST";
export const  RESELLER_APPROVE_SUCCESS = "RESELLER_APPROVE_SUCCESS";
export const  RESELLER_APPROVE_FAIL = "RESELLER_APPROVE_FAIL";
export const  RESELLER_APPROVE_RESET = "RESELLER_APPROVE_RESET";



export const CLEAR_ERRORS = "CLEAR_ERRORS";