export const GET_ADMIN_SUBSCRIBERS_REQUEST = "GET_ADMIN_SUBSCRIBERS_REQUEST";
export const GET_ADMIN_SUBSCRIBERS_SUCCESS = "GET_ADMIN_SUBSCRIBERS_SUCCESS";
export const GET_ADMIN_SUBSCRIBERS_FAIL = "GET_ADMIN_SUBSCRIBERS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";