export const  CREATE_TESTIMONIAL_REQUEST = "CREATE_TESTIMONIAL_REQUEST";
export const  CREATE_TESTIMONIAL_SUCCESS = "CREATE_TESTIMONIAL_SUCCESS";
export const  CREATE_TESTIMONIAL_FAIL = "CREATE_TESTIMONIAL_FAIL";


export const GET_ADMIN_TESTIMONIAL_REQUEST = "GET_ADMIN_TESTIMONIAL_REQUEST";
export const GET_ADMIN_TESTIMONIAL_SUCCESS = "GET_ADMIN_TESTIMONIAL_SUCCESS";
export const GET_ADMIN_TESTIMONIAL_FAIL = "GET_ADMIN_TESTIMONIAL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";